-- MySQL Script generated by MySQL Workbench -- Tue Feb 21 09:09:53 2023 -- Model: New Model Version: 1.0 -- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0; SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0; SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- Schema mydb

-- Schema mydb

CREATE SCHEMA IF NOT EXISTS mydb DEFAULT CHARACTER SET utf8 ; USE mydb ;

-- Table mydb.book

CREATE TABLE IF NOT EXISTS mydb.book ( id INT NOT NULL, title VARCHAR(45) NOT NULL, price VARCHAR(45) NOT NULL, author VARCHAR(45) NOT NULL, stock INT NOT NULL, ageRating INT NULL, PRIMARY KEY (id)) ENGINE = InnoDB;

-- Table mydb.customer

CREATE TABLE IF NOT EXISTS mydb.customer ( id INT , name VARCHAR(45) NOT NULL, alter INT NOT NULL, PRIMARY KEY (id)) ENGINE = InnoDB;

-- Table mydb.transaction

CREATE TABLE IF NOT EXISTS mydb.transaction ( id INT , date DATETIME NULL, book VARCHAR(45) NULL, customer VARCHAR(45) NULL, PRIMARY KEY (id)) ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE; SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS; SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

Added elements so books can be borrowed

CREATE TABLE book ( id int NOT NULL, title varchar(45) NOT NULL, price varchar(45) NOT NULL, author varchar(45) NOT NULL, stock int NOT NULL, ageRating int NOT NULL, borrowed int NOT NULL, PRIMARY KEY (id) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE customer ( id int NOT NULL, name varchar(45) NOT NULL, age int NOT NULL, PRIMARY KEY (id) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE transaction ( id int NOT NULL, borrowDate datetime DEFAULT NULL, book varchar(45) DEFAULT NULL, customer varchar(45) DEFAULT NULL, returnDeadline datetime DEFAULT NULL, PRIMARY KEY (id) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;



INSERT into book (id,title,price,author,stock,ageRating)
VALUES (1,"Harry Potter",15,"JK Roling",5,12);
INSERT into book (id,title,price,author,stock,ageRating)
VALUES (2,"Harry Potter",15,"JK Roling",4,12);
INSERT into book (id,title,price,author,stock,ageRating)
VALUES (3,"Harry Potter",15,"JK Roling",8,12);
INSERT into book (id,title,price,author,stock,ageRating)
VALUES (4,"Harry Potter",15,"JK Roling",2,12);
INSERT into book (id,title,price,author,stock,ageRating)
VALUES (5,"Harry Potter",15,"JK Roling",3,12);
INSERT into book (id,title,price,author,stock,ageRating)
VALUES (6,"Harry Potter",15,"JK Roling",9,12);
INSERT into book (id,title,price,author,stock,ageRating)
VALUES (7,"Harry Potter",15,"JK Roling",2,12);
UPDATE book
SET stock=5
WHERE id=7;
INSERT into book (id,title,price,author,stock,ageRating)
VALUES (8,"Harry Potter",15,"JK Roling",2,12);
DELETE FROM book
WHERE id=8;

INSERT into customer (id,name,age)
VALUES (1,"Minh",25);
INSERT into customer (id,name,age)
VALUES (2,"Artur",45);
INSERT into customer (id,name,age)
VALUES (3,"Max",20);
INSERT into customer (id,name,age)
VALUES (4,"Jenny",27);
INSERT into customer (id,name,age)
VALUES (5,"Laura",22);

INSERT into transaction (id,date,book,customer)
VALUES (1,'01.01.2005',"Harry Potter","Minh");
INSERT into transaction (id,date,book,customer)
VALUES (2,'01.01.2007',"Harry Potter","Jenny");
INSERT into transaction (id,date,book,customer)
VALUES (3,'01.01.2006',"Harry Potter","Laura");


-- changed booknames and dates
UPDATE book
SET title= "Harry Potter 1"
WHERE id=1;
UPDATE book
SET title= "Harry Potter 2"
WHERE id=2;
UPDATE book
SET title= "Harry Potter 3"
WHERE id=3;
UPDATE book
SET title= "Harry Potter 4"
WHERE id=4;
UPDATE book
SET title= "Harry Potter 5"
WHERE id=5;
UPDATE book
SET title= "Harry Potter 6"
WHERE id=6;
UPDATE book
SET title= "Harry Potter 7"
WHERE id=7;
UPDATE transaction
SET borrowDate='2022.02.20 20:00:00'
WHERE id=1;
UPDATE transaction
SET borrowDate='2022.02.15 20:00:00'
WHERE id=2;
UPDATE transaction
SET borrowDate='2022.03.20 20:00:00'
WHERE id=3;
UPDATE transaction
SET book="Harry Potter 1"
WHERE id=1;
UPDATE transaction
SET book="Harry Potter 5"
WHERE id=2;
UPDATE transaction
SET book="Harry Potter 4"
WHERE id=3;
INSERT into transaction (id,borrowdate,book,customer)
VALUES (4,'18.02.2023',"Harry Potter 2","Laura");
INSERT into transaction (id,borrowdate,book,customer)
VALUES (5,'03.03.2023',"Harry Potter 4","Laura");
UPDATE transaction
SET borrowDate='2022.03.10 20:00:00'
WHERE id=4;UPDATE transaction
           SET borrowDate='2022.02.07 20:00:00'
           WHERE id=5;


SELECT  book.title
from transaction JOIN book
                      ON transaction.book=book.title
WHERE borrowdate between '2022.02.01 20:00:00' and '2022.03.31 20:00:00';


SELECT customer
from transaction JOIN book
                      ON transaction.book=book.title
WHERE title="Harry Potter 4";
